### ISSUE TITLE
Trying to use spanish model

### ISSUE THREAD

**Issue by bravecorvus** [cmusphinx/pocketsphinx-python#46]
I got the English model to work as I want it to. Next, I got the Spanish model from [here](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Spanish/). Basically, it contains a `es.dict`, a `cmusphinx-es-5.2` directory (equivalent to the en-us/en-us directory in the example from `README.md`),  and an `es-20k.lm.gz` file (which I used the sphinxbase `gunzip es-20k.lm.gz && sphinx_lm_convert -i es-20k.lm -o es.lm.bin` command to convert to the bin file).

Next, I recorded a Spanish phrase into a file called `spanish.raw`

Then, I formatted the python code as follows:

```python
from os import environ, path

from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *

MODELDIR = "/home/osboxes/testsphinx/spanish"
DATADIR = "/home/osboxes/testsphinx/spanish"

# Create a decoder with certain model
config = Decoder.default_config()
config.set_string('-hmm', path.join(MODELDIR, 'es-es/model_parameters/voxforge_es_sphinx.cd_ptm_4000'))
config.set_string('-lm', path.join(MODELDIR, 'es.lm.bin'))
config.set_string('-dict', path.join(MODELDIR, 'es.dict'))
decoder = Decoder(config)

# Decode streaming data.
jsgf = Jsgf(path.join(DATADIR, 'grammar.gram'))
rule = jsgf.get_rule('test.sentence')
fsg = jsgf.build_fsg(rule, decoder.get_logmath(), 7.5)
fsg.writefile('fsg.fsg')
decoder = Decoder(config)
decoder.set_fsg('fsg', fsg)
decoder.set_search('test')
decoder.start_utt()
stream = open(path.join(DATADIR, 'spanish.raw'), 'rb')
while True:
  buf = stream.read(1024)
  if buf:
    decoder.process_raw(buf, False, False)
  else:
    break
decoder.end_utt()
print ('Best hypothesis segments: ', [seg.word for seg in decoder.seg()])
```

The `grammar.gram` file is as follows:

```
#JSGF V1.0;
grammar test;
public <sentence> = ( A palabras necias oídos sordos );
```

However, when I run the program, I get this error:

```
....
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU -nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall -nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU -nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall -nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU -nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall -nan xRT
INFO: fsg_search.c(227): FSG(beam: -1080, pbeam: -1080, wbeam: -634; wip: -26, pip: 0)
ERROR: "fsg_search.c", line 141: The word 'A' is missing in the dictionary
INFO: fsg_search.c(265): TOTAL fsg 0.00 CPU -nan xRT
INFO: fsg_search.c(268): TOTAL fsg 0.00 wall -nan xRT
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    decoder.set_fsg('fsg', fsg)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx-0.0.9-py2.7-linux-x86_64.egg/pocketsphinx/pocketsphinx.py", line 384, in set_fsg
    return _pocketsphinx.Decoder_set_fsg(self, name, fsg)
RuntimeError: Decoder_set_fsg returned -1
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU -nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall -nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU -nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall -nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU -nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall -nan xRT
....
```

Any idea what is causing this? I am assuming that since pocketsphinx-python is just a Swig wrapper interface (C -> Python), anything that is possible in standard pocketsphinx should also be possible in pocketsphinx-python.

Thanks for your help.

**Comment by gilgameshskytrooper** [comment]
nvm

**Comment by gilgameshskytrooper** [comment]
jk

**Comment by nshmyrev** [comment]
Line with error in the log should give you a hint.

The code you found is senseless too. You either need FSG or LM, not both.

**Comment by bravecorvus** [comment]
Okay thank you.
