### ISSUE TITLE
ImportError: cannot import name 'LiveSpeech' from 'pocketsphinx'

### ISSUE THREAD

**Issue by vishless** [cmusphinx/pocketsphinx-python#54]
After installing pocketsphinx via pip I tired to run the basic example
```

from pocketsphinx import LiveSpeech
for phrase in LiveSpeech(): print(phrase)
```

And I got this 

```

$ python pocketsphinx.py
Traceback (most recent call last):
  File "pocketsphinx.py", line 1, in <module>
    from pocketsphinx import LiveSpeech
  File "C:\Users\Vishnu\Desktop\pocketsphinx.py", line 1, in <module>
    from pocketsphinx import LiveSpeech
ImportError: cannot import name 'LiveSpeech' from 'pocketsphinx' (C:\Users\Vishnu\Desktop\pocketsphinx.py)
```

**Comment by raikk** [comment]
Did you fix it??

**Comment by nshmyrev** [comment]
PIP package is maintained here:

https://github.com/bambocher/pocketsphinx-python

**Comment by rishabh991** [comment]
https://anaconda.org/conda-forge/pocketsphinx-python
