### ISSUE TITLE
ERROR: "acmod.c", line 79: does not contain acoustic model definition 'mdef'

### ISSUE THREAD

**Issue by tiancaipipi110** [cmusphinx/pocketsphinx-python#58]
I'm getting this error 
```
INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='live', VARNORM='no', AGC='none'
ERROR: "acmod.c", line 79: Folder 'C:/Users/junew/Desktop/pocketsphinx-5prealpha/pocketsphinx/model/en-us/en-us\en-us/en-us' does not contain acoustic model definition 'mdef'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pocketsphinx\pocketsphinx.py", line 272, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```

**Comment by tiancaipipi110** [comment]
Alright, the sample code in `readme` shall add `'/'` in the end, like this. 
```
MODELDIR = "pocketsphinx/model/"
DATADIR = "pocketsphinx/test/data/"
```
