### ISSUE TITLE
cannot open shared object file: No such file or directory on pcoketsphinx

### ISSUE THREAD

**Issue by titusjoyson** [cmusphinx/pocketsphinx-python#6]
I installed as you directed and when i tried to run the sample file I got the below error how to fix this on ubuntu 15. Please reply as soon as possible. 

python test.py 

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from pocketsphinx.pocketsphinx import *
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/**init**.py", line 37, in <module>
    from pocketsphinx import *
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 42, in <module>
    _pocketsphinx = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 38, in swig_import_helper
    _mod = imp.load_module('_pocketsphinx', fp, pathname, description)
ImportError: libpocketsphinx.so.3: cannot open shared object file: No such file or directory

**Comment by nshmyrev** [comment]
The error message tells you that the system failed to load shared library libpocketsphinx.so.3. You have to configure linker to look in /usr/local/lib to load shared libraries. You can do it with LD_LIBRARY_PATH environment variable or with configuration file /etc/ld.so.conf

To learn more about shared libraries in Linux read 

http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
